const assert = require('node:assert/strict');
const fs = require('node:fs');
const path = require('node:path');
const {chromium} = require(process.env.RW_PLAYWRIGHT_MODULE || 'playwright-core');
(async () => {
  const browser = await chromium.launch({headless: true, ...(process.env.RW_BROWSER_PATH ? {executablePath: process.env.RW_BROWSER_PATH} : {})});
  const page = await browser.newPage({viewport: {width: 1440, height: 1050}, deviceScaleFactor: 1});
  const errors = [];
  page.on('pageerror', e => errors.push(String(e)));
  const base = process.env.RW_UI_URL || 'http://127.0.0.1:7030';
  await page.goto(base);
  await page.locator('#auth-dialog[open]').waitFor();
  await page.locator('#auth-token').fill('wrong-token');
  await page.locator('#login-button').click();
  await page.locator('#auth-error:not([hidden])').waitFor();
  await page.locator('#auth-token').fill(process.env.RW_UI_TOKEN || 'requestwatch-local-demo-7030');
  await page.locator('#login-button').click();
  await page.locator('#auth-dialog[open]').waitFor({state: 'hidden'});
  await page.locator('#records-body tr').first().waitFor();
  assert(await page.locator('#demo-badge').isVisible());
  await page.locator('#filter-query').fill('ORD-2048');
  await page.waitForFunction(() => !document.querySelector('#record-count').textContent.includes('加载') && document.querySelectorAll('#records-body tr').length === 2);
  await page.locator('#records-body tr').filter({hasText: 'POST'}).first().click();
  await page.locator('#edit-button').click();
  await page.locator('#edit-body').fill('界面草稿保留验证');
  await page.waitForTimeout(2300);
  assert.equal(await page.locator('#edit-body').inputValue(), '界面草稿保留验证');
  await page.locator('#replay-button').click();
  await page.locator('#confirm-ok').click();
  await page.waitForFunction(() => document.querySelector('#detail-state').textContent.includes('已重发'));
  await page.locator('[data-tab="request"]').click();
  assert((await page.locator('#detail-body').textContent()).includes('界面草稿保留验证'));
  await page.locator('.navigation [data-view="rules"]').click();
  await page.locator('#new-rule').click();
  await page.locator('#rule-name').fill('UI 验证 · 待审请求');
  await page.locator('#rule-source').selectOption('http');
  await page.locator('#rule-protocol').selectOption('HTTPS');
  await page.locator('#rule-keyword').fill('ui-probe');
  await page.locator('#rule-timeout').fill('120');
  await page.locator('#save-rule').click();
  await page.locator('#rule-dialog[open]').waitFor({state: 'hidden'});
  await page.locator('#generate-demo-request').click();
  await page.locator('#pending-actions:not([hidden])').waitFor();
  await page.locator('#edit-button').click();
  await page.locator('#edit-body').fill('UI 已批准');
  await page.locator('#accept-button').click();
  await page.waitForFunction(() => document.querySelector('#detail-state').textContent.includes('已放行'));
  await page.locator('[data-tab="request"]').click();
  assert((await page.locator('#detail-body').textContent()).includes('UI 已批准'));
  await page.locator('.navigation [data-view="rules"]').click();
  await page.locator('#generate-demo-request').click();
  await page.locator('#pending-actions:not([hidden])').waitFor();
  await page.locator('#drop-button').click();
  if (await page.locator('#confirm-dialog').isVisible()) await page.locator('#confirm-ok').click();
  await page.waitForFunction(() => document.querySelector('#detail-state').textContent.includes('已丢弃'));
  await page.locator('.navigation [data-view="containers"]').click();
  await page.locator('.container-card').first().waitFor();
  assert.equal(await page.locator('.container-card').count(), 2);
  await page.locator('.navigation [data-view="traffic"]').click();
  await page.locator('#reset-filters').click();
  await page.locator('#records-body tr').first().waitFor();
  await page.locator('#records-body tr').filter({hasText: '/v1/orders'}).first().click();
  await page.locator('[data-tab="response"]').click();
  fs.mkdirSync('artifacts', {recursive: true});
  await page.waitForTimeout(5200);
  await page.evaluate(() => window.scrollTo(0, 0));
  await page.screenshot({path: 'artifacts/webui-desktop.png', fullPage: true});
  await page.setViewportSize({width: 390, height: 844});
  await page.screenshot({path: 'artifacts/webui-mobile.png', fullPage: true});
  const overflow = await page.evaluate(() => document.documentElement.scrollWidth > window.innerWidth + 1);
  assert.equal(overflow, false, 'Mobile document overflow');
  const guide = page.locator('.mobile-guide-link');
  if (await guide.count()) { await guide.click(); await page.locator('#view-guide:not([hidden])').waitFor(); }
  assert.deepEqual(errors, [], 'Unexpected browser errors');
  console.log('WebUI passed: authentication, content search, preserved drafts, replay, rules, edit/accept, drop, containers, responsive layout.');
  await browser.close();
})().catch(error => { console.error(error); process.exit(1); });
